server:
  port: 8080

spring:
  application:
    name: service-cloudgateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${USER_EUREKA}:${PASSWORD_EUREKA}@${EUREKA_SERVER:localhost}:8761/eureka/